### ISSUE TITLE
Report message URL

### ISSUE THREAD

**Issue by spamegg1** [aroberge/friendly#201]
**Describe the bug**
I noticed that messages are still telling the user to use the old URL https://github.com/aroberge/friendly-traceback/issues
That URL correctly redirects to https://github.com/aroberge/friendly/issues but should it be changed in the source?
I mean... it's not exactly a bug I guess, but I can make a simple PR if you like.

**Expected behavior**
Correct URL should be displayed in the message.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/4255997/112686590-3f614300-8e87-11eb-8c02-8472cd999d88.png)

**Which Python version and Friendly version are you using**
Python=3.9 
friendly = "^0.3.12"

**Comment by aroberge** [comment]
If you want to do it, you can go ahead. But it's on my list of things to do and I will probably get to it this weekend. For me, it will be a simple search and replace, followed by undating the language file so that it can be translated).  I **do** appreciate the reminder, indicating that this should be taken care of sooner rather than later.

So, to sum up: feel free to make a PR, but even if you do not, I do appreciate the fact that you filed this issue.

**Comment by spamegg1** [comment]
Thanks, I guess I will leave it to you then!

**Comment by aroberge** [comment]
Thanks for the extra motivation. Three links have been updated in the original and French translation.
